# Generated by Django 5.1.3 on 2024-11-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('identifier', models.CharField(max_length=1)),
                ('player1_id', models.IntegerField()),
                ('player2_id', models.IntegerField()),
                ('state', models.CharField(max_length=256)),
                ('round', models.IntegerField()),
                ('loser_id', models.IntegerField(null=True)),
                ('group_id', models.IntegerField(null=True)),
                ('tournament_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.IntegerField()),
                ('group_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=256)),
                ('tournament_id', models.IntegerField()),
                ('challonge_username', models.CharField(max_length=256, null=True)),
                ('username', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=9999)),
                ('created_at', models.DateField()),
                ('state', models.CharField(max_length=256)),
                ('swiss_rounds', models.IntegerField()),
                ('started_at', models.DateField()),
                ('start_at', models.DateField(null=True)),
                ('participants_locked', models.BooleanField()),
                ('participants_swappable', models.BooleanField()),
            ],
        ),
    ]
